" Vundle configuration
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'flazz/vim-colorschemes'
" plugin from http://vim-scripts.org/vim/scripts.html
" Git plugin not hosted on GitHub
Plugin 'wincent/Command-T'
Plugin 'dhruvasagar/vim-table-mode'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin '/Users/vincent/.vim/bundle'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

Bundle 'altercation/vim-colors-solarized'
" Bundle 'Valloric/YouCompleteMe'
Bundle 'vim-scripts/a.vim'
Bundle 'derekwyatt/vim-scala'
Bundle 'plasticboy/vim-markdown'
Bundle 'honza/vim-snippets'
"Bundle 'Rip-Rip/clang_complete'
Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
Bundle 'yegappan/grep'
Bundle 'christoomey/vim-tmux-navigator'
Bundle 'rking/ag.vim'
" Bundle 'rdnetto/YCM-Generator'
Bundle 'majutsushi/tagbar'
Bundle 'scrooloose/syntastic'
" Bundle 'jeaye/color_coded'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Common Settings
syntax on
set nu
set background=dark
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
let g:solarized_termcolors = 256
colorscheme solarized

let mapleader=","

" clang Settings
let g:clang_library_path = "/usr/lib/clang/10/lib/linux/libclang_rt.asan-x86_64.so"
let g:airline_section_b = '%{strftime("%c")}'


" ctrlp root marker
let g:ctrlp_root_markers = ['.git', '.hg', 'bzr']
let g:ctrlp_user_command = {
  \ 'types': {
    \ 1: ['.git', 'cd %s && git ls-files'],
    \ 2: ['.hg', 'hg --cwd %s locate -I .'],
    \ },
  \ 'fallback': 'find %s -type f',
  \ 'ignore': 1
  \ }
let g:color_coded_enabled = 1
map <C-n> :NERDTreeToggle<CR>
nmap <leader>p :CtrlP<cr>
nmap <leader>bb :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>
set hlsearch
autocmd BufWritePost .vimrc source %
